routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@home');
Route::post('/start', ['as' => 'start', 'uses' => 'IndexController@start']);
Route::get('/order/{hash}', ['as' => 'order', 'uses' => 'IndexController@order']);

Route::group(['prefix' => 'platform'], function () {
    Route::group(['namespace' => 'Admin', 'as' => 'admin.', 'middleware' => 'auth'], function () {
        Route::get('/', 'IndexController@dashboard');

        crudRoutes('projects', 'project', 'ProjectController');
        crudRoutes('clients', 'client', 'ClientController');

        Route::get('attachments/{project}/{client}', 'AttachmentController@all');
        Route::post('attachment/{project}/{client}', 'AttachmentController@upload');
        Route::put('attachment/{attachment}', 'AttachmentController@update');
        Route::delete('attachment/{attachment}', 'AttachmentController@delete');
        Route::get('attachment/download/{attachment}', 'AttachmentController@download');

        Route::get('project/{project}/quote', ['as' => 'projects.quote', 'uses' => 'ProjectController@quote']);
        Route::post('project/{project}/quote', ['as' => 'projects.quote.store', 'uses' => 'ProjectController@quoteStore']);
        Route::get('project/{project}/job', ['as' => 'projects.job', 'uses' => 'ProjectController@job']);
        Route::post('project/{project}/job', ['as' => 'projects.job.store', 'uses' => 'ProjectController@jobStore']);
    });

    Auth::routes();
});

function crudRoutes($resource, $resourceSingular, $controllerName) {
    Route::get('/' . $resource, ['as' => $resource, 'uses' => $controllerName . '@index']);
    Route::get('/' . $resource . '/create', ['as' => $resource . '.create', 'uses' => $controllerName . '@create']);
    Route::post('/' . $resource . '/create', ['as' => $resource . '.store', 'uses' => $controllerName . '@store']);
    Route::get('/' . $resource . '/edit/{' . $resourceSingular . '}', ['as' => $resource . '.edit', 'uses' => $controllerName . '@edit']);
    Route::post('/' . $resource . '/edit/{' . $resourceSingular . '}', ['as' => $resource . '.update', 'uses' => $controllerName . '@update']);
    Route::post('/' . $resource . '/delete/{' . $resourceSingular . '}', ['as' => $resource . '.delete', 'uses' => $controllerName . '@delete']);
}

app/Models/Project.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * App\Models\Project
 *
 * @property-read string $state_color
 * @mixin \Eloquent
 * @property int $id
 * @property string $status
 * @property string $comment
 * @property int $client_id
 * @property int $attachment_id
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Project whereId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Project whereStatus($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Project whereComment($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Project whereClientId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Project whereAttachmentId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Project whereCreatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Project whereUpdatedAt($value)
 * @property-read \App\Models\Client $client
 * @property-read \App\Models\Attachment $attachment
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Attachment[] $attachments
 * @property-read mixed $client_attachments
 * @property-read mixed $admin_attachments
 */
class Project extends Model
{
    protected $fillable = [
        'status',
        'comment',
        'client_id',
        'attachment_id',
    ];

    protected $appends = [
        'state_color',
    ];

    /**
     * @return string
     */
    public function getStateColorAttribute()
    {
        switch ($this->attributes['status']) {
            case 'CG':
                $color = 'warning';
                break;

            case 'CA':
                $color = 'success';
                break;

            case 'R':
                $color = 'danger';
                break;

            case 'F':
                $color = 'active';
                break;

            default:
            case 'IC':
                $color = 'info';
                break;
        }

        return  $color;
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function client()
    {
        return $this->belongsTo('App\Models\Client');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function attachment()
    {
        return $this->belongsTo('App\Models\Attachment');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function attachments()
    {
        return $this->hasMany('App\Models\Attachment');
    }

    /**
     * @return mixed
     */
    public function getClientAttachmentsAttribute()
    {
        return $this->attachments()->where('user_provided', 1)->get();
    }

    /**
     * @return mixed
     */
    public function getAdminAttachmentsAttribute()
    {
        return $this->attachments()->where('user_provided', 0)->get();
    }
}

app/Http/Controllers/Admin/ProjectController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Mail\QuoteCreated;
use App\Models\Order;
use App\Models\Project;
use App\Models\ProjectActivity;
use App\Models\ProjectStates;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Alert;
use Mail;

class ProjectController extends Controller
{
    /**
     * 
     * @param Request $request
     * @return type
     */
    public function index(Request $request)
    {
        $query = Project::query()->with('client');
        $query->orderBy($request->query('order', 'created_at'), $request->query('sort', 'DESC'));

        return view('admin.projects.index', [
            'projects' => $query->paginate($request->query('per_page', 20)),
        ]);
    }

    /**
     * 
     * @return type
     */
    public function create()
    {
        return abort(404);
    }

    /**
     * 
     * @return type
     */
    public function store()
    {
        return abort(404);
    }

    /**
     * 
     * @param Request $request
     * @param Project $project
     * @return type
     */
    public function edit(Request $request, Project $project)
    {
        return view('admin.projects.edit', [
            'project' => $project,
            'attachments' => $project->attachments(),
        ]);
    }

    /**
     * @param Request $request
     * @param Project $project
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, Project $project)
    {
        $this->validate($request, [
            'comment' => 'sometimes',
        ]);

        $project->comment = $request->input('comment', '');
        $project->save();

        ProjectActivity::create([
            'project_id' => $project->id,
            'description' => trans('activity.project_activity.project_updated'),
        ]);

        Alert::success('Los cambios han sido guardados!')->autoclose(3000);

        return redirect()->route('admin.projects.edit', ['project' => $project]);
    }

    /**
     * @param Request $request
     * @param Project $project
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function quote(Request $request, Project $project)
    {
        return view('admin.projects.quote', ['project' => $project]);
    }

    /**
     * @param Request $request
     * @param Project $project
     * @return \Illuminate\Http\RedirectResponse
     */
    public function quoteStore(Request $request, Project $project)
    {
        $this->validate($request, [
            'subject' => 'required',
            'body' => 'required',
            'amount' => 'required',
        ]);

        $order = Order::create([
            'project_id' => $project->id,
            'order' => str_random(20),
            'transaction_reference' => null,
            'amount' => $request->input('amount'),
            'currency' => 'CLP',
            'status' => 0,
            'order_data' => [],
            'response_data' => [],
            'gateway' => null,
            'payment_date' => null,
            'extra' => ['currency' => 'CLP'],
        ]);

        Mail::to($project->client)->send(new QuoteCreated($project, $request, $order));

        $project->status = ProjectStates::STATE_QUOTE_GENERATED;
        $project->save();

        ProjectActivity::create([
            'project_id' => $project->id,
            'description' => trans('activity.project_activity.quote_sent', ['date' => Carbon::now()->format('d/m/Y H:i:s')]),
        ]);

        Alert::success('La cotizacion ha sido enviada')->autoclose(3000);

        return redirect()->route('admin.projects.edit', ['project' => $project]);
    }
}

resources/views/admin/projects/edit.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">
        <div class="row">

            <div class="page-header">
                <h1>{{ trans('admin.projects.title') }} - <small>{{ $project->created_at->format('d/m/Y H:i') }}</small></h1>
            </div>

            {!! Form::model($project, ['method' => 'post', 'class' => 'form-horizontal', 'url' => route('admin.projects.update', ['project' => $project])]) !!}

                <div class="col-md-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <span class="fa {{ $project->client->client_type === \App\Models\Client::CLIENT_TYPE_PERSON ? 'fa-user' : 'fa-building' }}"></span>
                            &nbsp;{{ $project->client->name }}
                            @if ($project->status === \App\Models\ProjectStates::STATE_QUOTE_GENERATED)
                                <span class="label label-success">{{ trans('admin.projects.quote.quote_already_exists') }}</span>
                            @endif
                        </div>

                        <div class="panel-body">
                            <dl class="">
                                @if ($project->client->client_type === \App\Models\Client::CLIENT_TYPE_COMPANY)
                                    <dt>{{ trans('admin.projects.contact_name') }}</dt>
                                    <dd>{{ $project->client->contact_name }}</dd>
                                @endif

                                <dt>{{ trans('admin.projects.email') }}</dt>
                                <dd>{{ $project->client->email }}</dd>
                            </dl>

                            <div class="">
                                <label for="comment" class="control-label">{{ trans('admin.projects.comment') }}</label>
                                {!! Form::textarea('comment', null, ['class' => 'form-control', 'rows' => 2]) !!}
                            </div>

                            <hr >
                            <div class="">
                                <button type="submit" class="btn btn-primary">{{ trans('form.save_comment_button') }}</button>
                                <a href="{{ route('admin.projects.quote', ['project' => $project]) }}" class="btn btn-info">{{ trans('form.send_quote_button') }}</a>
                                <a href="{{ route('admin.projects.job', ['project' => $project]) }}" class="btn btn-info">{{ trans('form.send_job_button') }}</a>
                            </div>
                        </div>
                    </div>
                </div>

            {!! Form::close() !!}

            <div class="col-md-12">
                <div class="page-header">
                    <h1>{{ trans('admin.projects.project_documents') }}</h1>
                </div>

                <div class="col-md-6">
                    <attachmentlist :client="1" :project="{{ $project->id }}" title="{{ trans('admin.projects.client_docs') }}" :attachment-types="{{ \App\Models\AttachmentType::get(['id', 'name']) }}"></attachmentlist>
                </div>

                <div class="col-md-6">
                    <attachmentlist :client="0" :project="{{ $project->id }}" title="{{ trans('admin.projects.admin_docs') }}" :attachment-types="{{ \App\Models\AttachmentType::get(['id', 'name']) }}"></attachmentlist>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/projects/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">
        <div class="row">

            <div class="page-header">
                <h1>{{ trans('admin.projects.title') }}</h1>
            </div>

            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>#</th>
                    <th>{{ trans('admin.projects.table.client_name') }}</th>
                    <th>{{ trans('admin.projects.table.created_at') }}</th>
                    <th>{{ trans('admin.projects.table.status') }}</th>
                    <th>{{ trans('admin.projects.table.options') }}</th>
                </tr>
                </thead>

                <tbody>
                @if ($projects->total() > 0)
                    @foreach($projects as $project)
                        <tr class="{{  $project->state_color }}">
                            <td>{{ $project->id }}</td>
                            <td>{{ $project->client->name }}</td>
                            <td>{{ $project->created_at->format('d-m-Y H:i') }}</td>
                            <td>
                                {{ !empty($project->status) ? $project->status : '--' }}
                                @if (!empty($project->status))
                                    <sup><small><span class="fa fa-question-circle" data-toggle="tooltip" title="{{ \App\Models\ProjectStates::states($project->status)->name }}"></span></small></sup>
                                @endif
                            </td>
                            <td>
                                <a href="{{ route('admin.projects.edit', ['project' => $project->id]) }}" class="btn btn-info btn-sm"><span class="fa fa-pencil"></span></a>
                            </td>
                        </tr>
                    @endforeach
                @else
                    <tr>
                        <td colspan="5" class="text-center">
                            <p>{{ trans('admin.projects.table.no_results_msg') }}</p>
                        </td>
                    </tr>
                @endif
                </tbody>
            </table>

            {!! $projects !!}
        </div>
    </div>
@endsection

resources/views/admin/projects/quote.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">
        <div class="row">

            <div class="page-header">
                <h1>{{ trans('admin.projects.quote.title') }} - <small>{{ $project->created_at->format('d/m/Y H:i') }}</small></h1>
            </div>

            {!! Form::model($project, ['method' => 'post', 'class' => 'form-horizontal', 'url' => route('admin.projects.quote.store', ['project' => $project])]) !!}

                <div class="col-md-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <span class="fa {{ $project->client->client_type === \App\Models\Client::CLIENT_TYPE_PERSON ? 'fa-user' : 'fa-building' }}"></span>
                            &nbsp;{{ $project->client->name }}
                            @if ($project->status === \App\Models\ProjectStates::STATE_QUOTE_GENERATED)
                                <span class="label label-success">{{ trans('admin.projects.quote.quote_already_exists') }}</span>
                            @endif
                        </div>

                        <div class="panel-body">
                            <dl class="">
                                @if ($project->client->client_type === \App\Models\Client::CLIENT_TYPE_COMPANY)
                                    <div class="form-group">
                                        <label class="control-label col-md-3">{{ trans('admin.projects.contact_name') }}</label>
                                        <div class="col-md-9">
                                            <p class="form-control-static">{{ $project->client->contact_name }}</p>
                                        </div>
                                    </div>
                                @endif

                                <div class="form-group">
                                    <label class="control-label col-md-3">{{ trans('admin.projects.email') }}</label>
                                    <div class="col-md-9">
                                        <p class="form-control-static">{{ $project->client->email }}</p>
                                    </div>
                                </div>
                            </dl>

                            <div class="form-group {{ $errors->has('subject') ? 'has-error' : '' }}">
                                <label for="comment" class="control-label col-md-3">{{ trans('form.quote.subject') }}</label>
                                <div class="col-md-5">
                                    {!! Form::text('subject', null, ['class' => 'form-control', 'rows' => 2]) !!}
                                </div>
                                @if ($errors->has('subject'))
                                    {!! $errors->first('subject', '<p class="col-md-offset-3 col-md-9">:message</p>') !!}
                                @endif
                            </div>

                            <div class="form-group {{ $errors->has('body') ? 'has-error' : '' }}">
                                <label for="comment" class="control-label col-md-3">{{ trans('form.quote.body') }}</label>
                                <div class="col-md-9">
                                    <textarea id="summernote" name="body"></textarea>
                                </div>
                                @if ($errors->has('body'))
                                    {!! $errors->first('body', '<p class="col-md-offset-3 col-md-9 text-error">:message</p>') !!}
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="comment" class="control-label col-md-3">{{ trans('form.quote.select_files') }}</label>
                                <div class="col-md-9">
                                    <h3>{{ trans('admin.projects.client_docs') }} ({{ $project->clientAttachments->count() }})</h3>
                                    @foreach ($project->clientAttachments as $attachment)
                                        <div class="checkbox">
                                            <label>
                                                {!! Form::checkbox('files[]', $attachment->id) !!} <strong>{{ $attachment->filename }}</strong> <em>({{ $attachment->attachmentType->name }})</em>
                                            </label>
                                        </div>
                                    @endforeach

                                    <hr>
                                    <h3>{{ trans('admin.projects.admin_docs') }} ({{ $project->adminAttachments->count() }})</h3>
                                    @foreach ($project->adminAttachments as $attachment)
                                        <div class="checkbox">
                                            <label>
                                                {!! Form::checkbox('files[]', $attachment->id) !!} <strong>{{ $attachment->filename }}</strong> <em>({{ $attachment->attachmentType->name }})</em>
                                            </label>
                                        </div>
                                    @endforeach
                                </div>
                            </div>

                            <div class="form-group {{ $errors->has('amount') ? 'has-error' : '' }}">
                                <label for="amount" class="control-label col-md-3">Monto Cotización</label>
                                <div class="col-md-9">
                                    <div class="input-group">
                                        <span class="input-group-addon">CLP $</span>
                                        {!! Form::text('amount', '0', ['class' => 'form-control']) !!}
                                    </div>
                                </div>
                                @if ($errors->has('amount'))
                                    {!! $errors->first('amount', '<p class="col-md-offset-3 col-md-9 text-error">:message</p>') !!}
                                @endif
                            </div>

                            <hr >
                            <div class="col-md-offset-3 col-md-9">
                                <button type="submit" class="btn btn-primary">{{ trans('form.send_quote_button') }}</button>
                            </div>
                        </div>
                    </div>
                </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

@section('inlinescript')
    <link href="//cdnjs.cloudflare.com/ajax/libs/summernote/0.8.2/summernote.css" rel="stylesheet">
    <script src="//cdnjs.cloudflare.com/ajax/libs/summernote/0.8.2/summernote.js"></script>
    <script>
        $(document).ready(function() {
            $('#summernote').summernote();
        });
    </script>
@endsection